#!/usr/bin/env python3
"""
Focus State Random Forest Model Training Script
Trains a Random Forest classifier on collected facial feature data.

Usage:
    python train_model.py
    
Requirements:
    - focus_data.csv (generated by collect_data.py)
    - At least 100 samples (ideally 500+)
"""

import pandas as pd  # type: ignore
from sklearn.ensemble import RandomForestClassifier  # type: ignore
from sklearn.model_selection import train_test_split  # type: ignore
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report  # type: ignore
import joblib  # type: ignore
import sys
import os

def main():
    print("=" * 70)
    print("Focus State Random Forest Model Training")
    print("=" * 70)

    # Check if CSV file exists
    csv_file = 'focus_data.csv'
    if not os.path.exists(csv_file):
        print(f"[ERROR] {csv_file} not found!")
        print("[INFO] Please run collect_data.py first to collect training data")
        sys.exit(1)

    # Load data
    try:
        data = pd.read_csv(csv_file)
        print(f"[INFO] Loaded {len(data)} samples from {csv_file}")
    except Exception as e:
        print(f"[ERROR] Failed to load {csv_file}: {e}")
        sys.exit(1)

    # Check minimum samples
    if len(data) < 50:
        print(f"[WARNING] Only {len(data)} samples found. Recommended: 500+")
        print("[WARNING] Model performance may be poor with limited data")

    # Display data distribution
    print("\n[DATA] Sample distribution:")
    for label in data['Label'].unique():
        count = (data['Label'] == label).sum()
        pct = (count / len(data)) * 100
        print(f"  {label}: {count} samples ({pct:.1f}%)")

    # Prepare features and labels
    X = data[['EAR', 'MAR', 'Pitch', 'Yaw']]
    y = data['Label']

    print(f"\n[FEATURES] Using: EAR, MAR, Pitch, Yaw")
    print(f"[LABELS] Classes: {list(y.unique())}")

    # Handle missing values
    X = X.fillna(X.mean())

    # Split data
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y if len(data) > 10 else None
    )
    print(f"\n[SPLIT] Training: {len(X_train)} | Testing: {len(X_test)}")

    # Train Random Forest
    print("\n[TRAINING] Random Forest Classifier...")
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=15,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    )
    
    model.fit(X_train, y_train)
    print("[SUCCESS] Model training completed")

    # Evaluate model
    print("\n[EVALUATION] Model Performance:")
    print("=" * 70)
    
    y_pred = model.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_test, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_test, y_pred, average='weighted', zero_division=0)
    
    print(f"Accuracy:  {accuracy:.4f} ({accuracy*100:.2f}%)")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1 Score:  {f1:.4f}")

    # Confusion matrix
    print("\n[CONFUSION_MATRIX]")
    cm = confusion_matrix(y_test, y_pred)
    labels = sorted(y.unique())
    print("           " + " ".join(f"{l:>12}" for l in labels))
    for i, label in enumerate(labels):
        print(f"{label:>9} " + " ".join(f"{cm[i][j]:>12}" for j in range(len(labels))))

    # Classification report
    print("\n[CLASSIFICATION_REPORT]")
    print(classification_report(y_test, y_pred, zero_division=0))

    # Feature importance
    print("\n[FEATURE_IMPORTANCE]")
    feature_names = ['EAR', 'MAR', 'Pitch', 'Yaw']
    importances = model.feature_importances_
    for name, importance in zip(feature_names, importances):
        print(f"  {name}: {importance:.4f}")

    # Save model
    model_file = 'focus_model.pkl'
    try:
        joblib.dump(model, model_file)
        print(f"\n[SAVED] Model saved to {model_file}")
    except Exception as e:
        print(f"[ERROR] Failed to save model: {e}")
        sys.exit(1)

    print("=" * 70)
    print("[SUCCESS] Training completed successfully!")
    print("[NEXT] Move focus_model.pkl to your project folder and restart backend")
    print("=" * 70)

if __name__ == "__main__":
    main()
