"""
train_rupee_yolo.py — Indian Rupee Banknote YOLO Detector
==========================================================
Trains a lightweight YOLOv8n model to detect and classify all denominations
of current Indian Rupee banknotes in real time on the ESP32-CAM feed.

Denominations supported (7 classes):
  10, 20, 50, 100, 200, 500, 2000

─── DATASET SETUP ────────────────────────────────────────────────────────────
Option A — Use a public Kaggle dataset (recommended):
  1. Install kaggle CLI:   pip install kaggle
  2. Download:             kaggle datasets download -d prashant268/indian-currency-note-dataset
  3. Unzip into:           datasets/rupee/
  4. Convert annotations to YOLO format (see convert_annotations() below)

Option B — Collect your own (best accuracy for your camera):
  1. Run:   python collect_rupee_data.py   (script below auto-creates it)
  2. Label with LabelImg:  pip install labelImg && labelImg
  3. Save YOLO format labels in datasets/rupee/train/labels/

Dataset structure expected:
  datasets/
    rupee/
      data.yaml
      train/
        images/   *.jpg
        labels/   *.txt   (YOLO format: class cx cy w h, normalised)
      val/
        images/
        labels/

─── QUICK START ──────────────────────────────────────────────────────────────
  # 1. Activate virtual env
  source train_env/bin/activate

  # 2. Run this script
  python train_rupee_yolo.py

  # 3. Best model is copied to rupee_model.pt  →  backend auto-detects it

─── REQUIREMENTS ─────────────────────────────────────────────────────────────
  pip install ultralytics torch torchvision pillow
"""

import os
import sys
import shutil
import argparse
import textwrap
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────
CLASSES = ["10", "20", "50", "100", "200", "500", "2000"]   # YOLO class names
DATASET_ROOT  = Path("datasets/rupee")
OUTPUT_MODEL  = Path("rupee_model.pt")
EPOCHS        = 80          # increase to 150 for better accuracy if you have GPU
IMGSZ         = 416         # ESP32-CAM captures 640×480; 416 is a good trade-off
BATCH         = 16          # reduce to 8 if CUDA OOM
PATIENCE      = 20          # early stopping — stops if val/mAP doesn't improve
BASE_MODEL    = "yolov8n.pt"  # nano — fastest; swap for yolov8s.pt if GPU available
CONF_THRESH   = 0.40        # minimum confidence for export


# ─────────────────────────────────────────────────────────────────────────────
# Auto-generate data.yaml
# ─────────────────────────────────────────────────────────────────────────────
def write_data_yaml() -> Path:
    yaml_path = DATASET_ROOT / "data.yaml"
    yaml_text = textwrap.dedent(f"""\
        # Indian Rupee banknote detection — auto-generated by train_rupee_yolo.py
        path:  {DATASET_ROOT.resolve()}
        train: train/images
        val:   val/images

        nc: {len(CLASSES)}
        names: {CLASSES}
    """)
    yaml_path.write_text(yaml_text)
    print(f"[DATA] Wrote {yaml_path}")
    return yaml_path


# ─────────────────────────────────────────────────────────────────────────────
# Optional: convert simple bbox CSV/JSON → YOLO .txt labels
# ─────────────────────────────────────────────────────────────────────────────
def convert_annotations(src_dir: Path, dst_dir: Path, img_dir: Path) -> None:
    """
    Minimal converter for annotations saved as:
      <image_name>.txt with lines:  class_name x_center y_center width height
    where coordinates are already normalised 0-1 (LabelImg YOLO export format).

    If your dataset uses a different format (Pascal VOC XML, COCO JSON etc.),
    replace this function or use roboflow.com to convert for free.
    """
    dst_dir.mkdir(parents=True, exist_ok=True)
    converted = 0
    for ann_file in sorted(src_dir.glob("*.txt")):
        lines_out = []
        for line in ann_file.read_text().splitlines():
            parts = line.strip().split()
            if not parts:
                continue
            cls_name = parts[0]
            if cls_name not in CLASSES:
                print(f"  [WARN] Unknown class '{cls_name}' in {ann_file.name} — skipping line")
                continue
            cls_idx = CLASSES.index(cls_name)
            # Replace class name with integer index
            lines_out.append(f"{cls_idx} {' '.join(parts[1:])}")
        if lines_out:
            (dst_dir / ann_file.name).write_text("\n".join(lines_out))
            converted += 1
    print(f"[DATA] Converted {converted} annotation files → {dst_dir}")


# ─────────────────────────────────────────────────────────────────────────────
# Dataset integrity check
# ─────────────────────────────────────────────────────────────────────────────
def check_dataset() -> bool:
    ok = True
    for split in ("train", "val"):
        img_dir = DATASET_ROOT / split / "images"
        lbl_dir = DATASET_ROOT / split / "labels"
        if not img_dir.exists():
            print(f"[ERROR] Missing: {img_dir}")
            ok = False
        if not lbl_dir.exists():
            print(f"[ERROR] Missing: {lbl_dir}")
            ok = False
        if ok:
            imgs   = list(img_dir.glob("*.jpg")) + list(img_dir.glob("*.png"))
            labels = list(lbl_dir.glob("*.txt"))
            print(f"[DATA] {split}: {len(imgs)} images, {len(labels)} label files")
            if len(imgs) == 0:
                print(f"[ERROR] No images found in {img_dir}")
                ok = False
    return ok


# ─────────────────────────────────────────────────────────────────────────────
# Data augmentation config (written to augment.yaml and passed to trainer)
# ─────────────────────────────────────────────────────────────────────────────
AUGMENT_ARGS = {
    # Geometric — simulate different hand angles & distances
    "degrees":    15.0,    # rotation ± 15°
    "translate":  0.15,    # translate ± 15%
    "scale":      0.6,     # scale 40%-160%
    "shear":      5.0,     # shear ± 5°
    "perspective": 0.001,  # slight perspective warp (as if tilting note)
    "flipud":     0.0,     # notes are always right-side up
    "fliplr":     0.5,     # horizontal flip is fine
    # Photometric — simulate ESP32-CAM lighting variations
    "hsv_h":      0.02,    # small hue shift
    "hsv_s":      0.7,     # saturation jitter
    "hsv_v":      0.5,     # brightness jitter (handles glare / dim lighting)
    "mosaic":     1.0,     # mosaic (4-image) augmentation — crucial for small datasets
    "mixup":      0.15,    # MixUp blending
}


# ─────────────────────────────────────────────────────────────────────────────
# Training
# ─────────────────────────────────────────────────────────────────────────────
def train(args: argparse.Namespace) -> None:
    try:
        from ultralytics import YOLO
    except ImportError:
        print("[ERROR] ultralytics not installed. Run:  pip install ultralytics")
        sys.exit(1)

    # ── Dataset check ──────────────────────────────────────────────────────
    DATASET_ROOT.mkdir(parents=True, exist_ok=True)
    (DATASET_ROOT / "train" / "images").mkdir(parents=True, exist_ok=True)
    (DATASET_ROOT / "train" / "labels").mkdir(parents=True, exist_ok=True)
    (DATASET_ROOT / "val"   / "images").mkdir(parents=True, exist_ok=True)
    (DATASET_ROOT / "val"   / "labels").mkdir(parents=True, exist_ok=True)

    yaml_path = write_data_yaml()

    if not check_dataset():
        print()
        print("=" * 60)
        print("Dataset not ready. Steps to collect data:")
        print()
        print("  1. Photograph each denomination (10, 20, 50, 100, 200, 500, 2000)")
        print("     from different angles, distances, and lighting conditions.")
        print("     Target: ≥ 200 photos per denomination (1400 total minimum).")
        print()
        print("  2. Label with LabelImg:")
        print("     pip install labelImg && labelImg")
        print("     Select 'YOLO' output format, open datasets/rupee/train/images/")
        print()
        print("  3. Split: put 80% in train/, 20% in val/")
        print()
        print("  OR use a pre-labelled Kaggle dataset:")
        print("     kaggle datasets download -d prashant268/indian-currency-note-dataset")
        print("=" * 60)
        sys.exit(1)

    # ── Load base model ────────────────────────────────────────────────────
    print(f"\n[TRAIN] Starting YOLOv8n training on Indian Rupee dataset")
    print(f"[TRAIN] Epochs={args.epochs}  imgsz={args.imgsz}  batch={args.batch}")
    model = YOLO(args.base_model)

    # ── Train ──────────────────────────────────────────────────────────────
    results = model.train(
        data      = str(yaml_path),
        epochs    = args.epochs,
        imgsz     = args.imgsz,
        batch     = args.batch,
        patience  = PATIENCE,
        project   = "runs",
        name      = "rupee_detector",
        exist_ok  = True,
        # Augmentation
        **AUGMENT_ARGS,
        # Training hygiene
        optimizer = "AdamW",
        lr0       = 0.001,
        lrf       = 0.01,
        warmup_epochs = 3,
        label_smoothing = 0.05,
        # Faster training on CPU
        workers   = 4,
        amp       = True,    # automatic mixed precision (no-op on CPU, big speedup on GPU)
        verbose   = True,
    )

    # ── Export best model ──────────────────────────────────────────────────
    best_pt = Path("runs/rupee_detector/weights/best.pt")
    if best_pt.exists():
        shutil.copy(best_pt, OUTPUT_MODEL)
        print(f"\n[SUCCESS] Best model copied to {OUTPUT_MODEL}")
        print(f"[INFO]    mAP50 = {results.results_dict.get('metrics/mAP50(B)', 'N/A'):.4f}")  # type: ignore[union-attr]

        # Try ONNX export for faster CPU inference in backend
        try:
            onnx_model = YOLO(str(best_pt))
            onnx_path  = onnx_model.export(format="onnx", imgsz=args.imgsz, opset=17,
                                            simplify=True, dynamic=False)
            shutil.copy(onnx_path, "rupee_model.onnx")
            print(f"[SUCCESS] ONNX model exported to rupee_model.onnx")
            print("[INFO]    Backend will prefer rupee_model.onnx for faster CPU inference")
        except Exception as e:
            print(f"[INFO] ONNX export skipped: {e} — backend will use .pt")

        print()
        print("=" * 60)
        print("TRAINING COMPLETE")
        print(f"  Model:  {OUTPUT_MODEL}")
        print(f"  Restart backend.py to load the new rupee model.")
        print(f"  Then switch to Mode 1 and press 'Currency Reader' toggle in the UI.")
        print("=" * 60)
    else:
        print(f"[ERROR] best.pt not found at {best_pt} — check training logs")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train YOLOv8n on Indian Rupee banknotes for ZYGLASS Currency Reader"
    )
    parser.add_argument("--epochs",     type=int,   default=EPOCHS,     help=f"Training epochs (default {EPOCHS})")
    parser.add_argument("--imgsz",      type=int,   default=IMGSZ,      help=f"Input image size (default {IMGSZ})")
    parser.add_argument("--batch",      type=int,   default=BATCH,      help=f"Batch size (default {BATCH})")
    parser.add_argument("--base-model", type=str,   default=BASE_MODEL, help="Base YOLO model (default yolov8n.pt)")
    args = parser.parse_args()

    train(args)
